spring:
  application:
    name: caremoa_aftercare
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(dBpe4U48smRTsugGzYA4NHxKDDlPsVrG/y6uE5XbHtXssFInRkWeeNoP0ufVMk1Q2rV9zOQ0/3AUL3Px2Ve05ccqQAdnbGp30Zg1K/jz/QtSSoX/wnW29jQTuY5CZRMTlNJDnzynr8Qxk8FLGtCNsuRKRq7R0PlBDiYN+V/spzHpbvjicZAxFjG/KL7PyAvw)
    username: ENC(c+kcvDX8JFho6N8fAhzIiA==)
    password: ENC(ap9tR83A72LOBzD/fnbSFA==)
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    activate:
      # Local
      on-profile: default
      # Server
      # on-profile: docker

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug

# Jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor